# FABLE Pyculator 2021 FreshForge Run

This notebook shows how to use FABLE Pyculator to derive the 2021 FABLE-C output-ref boundary, then use FreshForge to run the Modelwright generated-model workflow.

## Local artifacts

The source workbook stays under ignored `tmp/` paths. The generated Python model and run evidence are written under `tmp/generated-models/fable-2021/`.

In [28]:
from __future__ import annotations

from pathlib import Path

from IPython.display import Markdown, display

from fable_pyculator import (
    build_2021_notebook_spec,
    build_cached_workbook_validation_scenario,
    build_modelwright_freshforge_workflow,
    derive_output_refs,
    freshforge_2021_build_paths,
    load_generated_model,
    run_notebook_loop,
    write_freshforge_workflow,
    write_output_refs,
    write_validation_scenario,
)


def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "pyproject.toml").exists() and (candidate / "src" / "fable_pyculator").exists():
            return candidate
    raise RuntimeError("Could not find the fable-pyculator repository root.")


repo_root = find_repo_root(Path.cwd().resolve())
paths = freshforge_2021_build_paths(repo_root=repo_root)
paths.artifact_dir.mkdir(parents=True, exist_ok=True)

workbook_path = paths.workbook_path
artifact_dir = paths.artifact_dir
output_refs_path = paths.output_refs_path
workflow_path = paths.workflow_path
generated_model_path = paths.generated_model_path
validation_scenario_path = paths.validation_scenario_path
evaluation_report_path = paths.evaluation_report_path

display(Markdown(f"Workbook path: `{workbook_path.relative_to(repo_root)}`"))
display(Markdown(f"Artifact directory: `{artifact_dir.relative_to(repo_root)}`"))

Workbook path: `tmp/private-workbooks/2021_Open_FABLECalculator.xlsx`

Artifact directory: `tmp/generated-models/fable-2021`

In [29]:
missing = [path for path in (workbook_path,) if not path.exists()]
ARTIFACTS_READY = not missing

if missing:
    display(Markdown("Missing local artifact(s):"))
    display([str(path.relative_to(repo_root)) for path in missing])
else:
    display(Markdown("Local 2021 workbook is ready."))

Local 2021 workbook is ready.

## Derive Modelwright output refs

FABLE Pyculator reads the FABLE output tables and selects workbook cells from columns tagged `OUTPUT-*`. Modelwright receives the resulting explicit `output_refs.json` file.

In [30]:
if ARTIFACTS_READY:
    fable_spec = build_2021_notebook_spec(workbook_path)
    output_refs = derive_output_refs(fable_spec, column_flavour_tags= None)
    write_output_refs(output_refs_path, output_refs)
    display(Markdown(f"Wrote `{len(output_refs):,}` output refs to `{output_refs_path.relative_to(repo_root)}`."))
    display(output_refs[:10])
else:
    output_refs = []
    display(Markdown("Restore the 2021 workbook before deriving output refs."))

Wrote `44,234` output refs to `tmp/generated-models/fable-2021/output_refs.json`.

('BIODIVERSITY!L14',
 'BIODIVERSITY!L15',
 'BIODIVERSITY!L16',
 'BIODIVERSITY!L17',
 'BIODIVERSITY!L18',
 'BIODIVERSITY!L19',
 'BIODIVERSITY!L20',
 'BIODIVERSITY!L21',
 'BIODIVERSITY!L22',
 'BIODIVERSITY!L23')

## Prepare cached-workbook validation

The validation scenario uses nonblank cached workbook values for the selected output refs.

In [31]:
if ARTIFACTS_READY and output_refs:
    validation_scenario = build_cached_workbook_validation_scenario(
        workbook_path,
        output_refs,
        generated_model_path=generated_model_path,
        scenario_id="fable-c-2021-freshforge-run",
        description="Cached-workbook validation slice derived from FABLE Pyculator OUTPUT-* refs.",
        source_workbook=workbook_path.relative_to(repo_root),
        generated_model=generated_model_path.relative_to(repo_root),
    )
    write_validation_scenario(validation_scenario_path, validation_scenario)
    display(Markdown(f"Wrote `{len(validation_scenario['outputs']):,}` validation outputs to `{validation_scenario_path.relative_to(repo_root)}`."))
else:
    display(Markdown("Restore the 2021 workbook and derive output refs before writing a validation scenario."))

Wrote `40,991` validation outputs to `tmp/generated-models/fable-2021/validation-scenario.json`.

## Declare the FreshForge workflow

This graph uses Modelwright provider nodes for contract inference, model generation, generated-model execution, and cached validation evaluation.

In [32]:
workflow_document = build_modelwright_freshforge_workflow(
    paths,
    workdir=repo_root,
    workflow_id="fable_2021_modelwright_run",
    name="FABLE 2021 Modelwright FreshForge run",
    description="FreshForge graph for rebuilding the 2021 FABLE generated model.",
    module_name="generated_fable_2021_model",
)
write_freshforge_workflow(workflow_path, workflow_document)
display(Markdown(f"Wrote FreshForge workflow graph to `{workflow_path.relative_to(repo_root)}`."))

Wrote FreshForge workflow graph to `tmp/generated-models/fable-2021/freshforge-modelwright-run-workflow.json`.

## Validate and plan

In [33]:
try:
    from freshforge.loading import load_workflow
    from freshforge.planning import create_run_plan

    FRESHFORGE_READY = True
except ModuleNotFoundError:
    FRESHFORGE_READY = False
    display(Markdown("FreshForge is not installed in this kernel."))

if FRESHFORGE_READY:
    workflow_spec, diagnostics = load_workflow(workflow_path)
    plan = create_run_plan(workflow_spec, diagnostics=diagnostics) if workflow_spec is not None else None
    display(plan.to_dict() if plan is not None else [diagnostic.to_dict() for diagnostic in diagnostics])
    if plan is None or plan.has_errors:
        raise RuntimeError("FreshForge could not plan the Modelwright workflow graph.")

{'workflow_id': 'fable_2021_modelwright_run',
 'nodes': [{'id': 'infer_contract',
   'provider': 'modelwright.model_infer_contract',
   'provider_id': 'modelwright',
   'node_type': 'model_infer_contract',
   'provider_available': True,
   'needs': []},
  {'id': 'generate_model',
   'provider': 'modelwright.model_generate',
   'provider_id': 'modelwright',
   'node_type': 'model_generate',
   'provider_available': True,
   'needs': ['infer_contract']},
  {'id': 'execute_model',
   'provider': 'modelwright.model_execute',
   'provider_id': 'modelwright',
   'node_type': 'model_execute',
   'provider_available': True,
   'needs': ['generate_model']},
  {'id': 'evaluate_model',
   'provider': 'modelwright.validation_evaluate',
   'provider_id': 'modelwright',
   'node_type': 'validation_evaluate',
   'provider_available': True,
   'needs': ['execute_model']}],
 'diagnostics': []}

## Run with FreshForge

The run is gated because the full 2021 build can take several minutes. Review the plan first, then set `RUN_FRESHFORGE = True`.

In [34]:
RUN_FRESHFORGE = True

if RUN_FRESHFORGE:
    if not ARTIFACTS_READY:
        raise RuntimeError("Restore the 2021 workbook before running the build.")
    from freshforge.execution import run_workflow
    from freshforge.loading import load_workflow

    workflow_spec, diagnostics = load_workflow(workflow_path)
    if workflow_spec is None:
        raise RuntimeError([diagnostic.to_dict() for diagnostic in diagnostics])
    run_result = run_workflow(workflow_spec, diagnostics=diagnostics, workdir=repo_root)
    display(run_result.to_dict())
    if not run_result.ok:
        raise RuntimeError("FreshForge run failed; inspect diagnostics above.")
else:
    display(Markdown("FreshForge run not started. Set `RUN_FRESHFORGE = True` after reviewing the plan."))

/home/gafar001/projets/fable-pyculator/.venv/lib/python3.12/site-packages/openpyxl/reader/drawings.py:67: UserWarning: wmf image format is not supported so the image is being dropped
  warn(msg)
/home/gafar001/projets/fable-pyculator/.venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

{'workflow_id': 'fable_2021_modelwright_run',
 'status': 'success',
 'nodes': [{'id': 'infer_contract',
   'provider': 'modelwright.model_infer_contract',
   'provider_id': 'modelwright',
   'node_type': 'model_infer_contract',
   'status': 'success',
   'outputs': {'generated_contract': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/contract.json',
    'formula_expressions': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/expressions.json',
    'input_constants': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/constants.json'},
   'artifacts': {'output_refs': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/output_refs.json',
    'contract': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/contract.json',
    'expressions': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/expressions.json',
    'constants': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/constants.json',
    'inference_result': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/inference-result.json'},
   'diagnostics': [],
   'data': {'inferred': True}},
  {'id': 'generate_model',
   'provider': 'modelwright.model_generate',
   'provider_id': 'modelwright',
   'node_type': 'model_generate',
   'status': 'success',
   'outputs': {'generated_model': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated_fable_2021_model.py'},
   'artifacts': {'contract': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/contract.json',
    'expressions': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/expressions.json',
    'constants': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/constants.json',
    'generated_model': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated_fable_2021_model.py',
    'generation_result': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generation-result.json'},
   'diagnostics': [],
   'data': {'generated': True}},
  {'id': 'execute_model',
   'provider': 'modelwright.model_execute',
   'provider_id': 'modelwright',
   'node_type': 'model_execute',
   'status': 'success',
   'outputs': {'generated_values': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated-values.json'},
   'artifacts': {'contract': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/contract.json',
    'generated_model': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated_fable_2021_model.py',
    'generated_values': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated-values.json'},
   'diagnostics': [],
   'data': {'executed': True}},
  {'id': 'evaluate_model',
   'provider': 'modelwright.validation_evaluate',
   'provider_id': 'modelwright',
   'node_type': 'validation_evaluate',
   'status': 'success',
   'outputs': {'validation_report': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/evaluation-report.json'},
   'artifacts': {'contract': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/contract.json',
    'generated_model': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated_fable_2021_model.py',
    'scenario': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/validation-scenario.json',
    'evaluation_report': '/srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/evaluation-report.json'},
   'diagnostics': [],
   'data': {'cached_validation_status': None}}],
 'diagnostics': []}

## Inspect FABLE Pyculator outputs

After the FreshForge run creates the 2021 generated model, load that exact generated artifact and inspect FABLE output tables/headlines.

In [35]:
if generated_model_path.exists() and ARTIFACTS_READY:
    generated_model = load_generated_model(
        generated_model_path,
        module_name="fable_pyculator_freshforge_generated_fable_2021",
    )
    result = run_notebook_loop(
        generated_model,
        fable_spec,
        {},
        scenario_name="freshforge-2021",
        include_figures=False,
    )
    display(Markdown(f"Rendered `{len(result.output_tables)}` output tables and `{len(result.headline_frames)}` headline frames."))
    display(result.output_tables["ghg_resultsghg"].head())
else:
    display(Markdown(f"Generated model not found yet: `{generated_model_path.relative_to(repo_root)}`"))

Rendered `14` output tables and `4` headline frames.

,Year,TotalCO2e,FAOTotalCO2e,AgriCO2e,AgriCO2,AgriN2O,TotalCH4,HistLiveCO2e,HistLiveN2O,HistLiveCH4,...,HistCropCH4,CropCO2e,CropCO2,CropN2O,CropCH4,LandCO2e,DeforCO2,OtherLandCO2,LandSeq,BiofuelSavings
row,,,,,,,,,,,,,,,,,,,,,
2000,2000,430.129794,446.298795,430.940352,39.366663,107.732802,283.840888,192.790133,63.613974,129.176158,...,161.144614,252.724015,39.366663,53.722517,159.634835,0.000000,0.000000,0.000000,0.000000,-0.810558
2005,2005,353.131735,464.753553,437.893670,41.446155,108.993847,287.453668,204.325454,67.543424,136.782031,...,165.705136,256.331049,41.446155,53.448830,161.436065,-83.632340,9.175123,2.260630,-95.068094,-1.129594
2010,2010,568.835838,500.444337,480.142758,42.028385,121.932689,316.181685,219.264165,72.799349,146.464816,...,179.774267,275.957602,42.028385,59.297512,174.631705,90.059210,92.819474,115.655618,-118.415882,-1.366130
2015,2015,458.011877,NaN,484.929746,41.887267,124.699828,318.342651,0.000000,0.000000,0.000000,...,0.000000,270.895936,41.887267,58.985037,170.023633,-25.215655,48.041020,54.498323,-127.754997,-1.702214
2020,2020,466.452938,NaN,492.955267,41.871528,127.264513,323.819226,0.000000,0.000000,0.000000,...,0.000000,272.509623,41.871528,59.549911,171.088184,-24.405715,59.224656,80.547175,-164.177546,-2.096614

In [36]:
result.output_tables["food_results_diets"].head(10)

,PROD_GROUP,YEAR,gr_hist,kcal_hist,gr_trend,kcal_trend,fat_trend,prot_trend,gr_calc,kcal_calc,fat_calc,prot_calc,gr_healthy,kcal_healthy
row,,,,,,,,,,,,,,
CEREALS,CEREALS,2000,389.703716,1397.825305,389.703716,1397.825305,4.243112,28.261134,389.703716,1397.825305,4.243112,28.261134,232.0,808.0
CEREALS,CEREALS,2005,397.850616,1427.614866,397.850616,1427.614866,4.343846,28.820913,397.850616,1427.614866,4.343846,28.820913,232.0,808.0
CEREALS,CEREALS,2010,399.632824,1434.034243,399.632824,1434.034243,4.385593,28.836216,399.632824,1434.034243,4.385593,28.836216,232.0,808.0
CEREALS,CEREALS,2015,,,389.036048,1396.008988,4.269303,28.071587,389.036048,1396.008988,4.269303,28.071587,232.0,808.0
CEREALS,CEREALS,2020,,,378.439272,1357.983734,4.153013,27.306958,378.439272,1357.983734,4.153013,27.306958,232.0,808.0
CEREALS,CEREALS,2025,,,357.245720,1281.933226,3.920434,25.777699,357.245720,1281.933226,3.920434,25.777699,232.0,808.0
CEREALS,CEREALS,2030,,,325.455392,1167.857463,3.571565,23.483812,325.455392,1167.857463,3.571565,23.483812,232.0,808.0
CEREALS,CEREALS,2035,,,283.068288,1015.756446,3.106407,20.425295,283.068288,1015.756446,3.106407,20.425295,232.0,808.0
CEREALS,CEREALS,2040,,,230.084407,825.630175,2.524959,16.602149,230.084407,825.630175,2.524959,16.602149,232.0,808.0
CEREALS,CEREALS,2045,,,187.697303,673.529158,2.059801,13.543632,187.697303,673.529158,2.059801,13.543632,232.0,808.0

In [39]:
from fable_pyculator import output_table_frame

if ARTIFACTS_READY:
    display(output_table_frame(result.run, "trade_resultstrade").head())

,PriceYear,PRODUCT,YEAR,ExportPrice,ImportPrice,ExportQ_targ,Exportvusd_targ,ExportQ_feas,Exportvusd_feas,ImportQ_feas,Importvusd
row,,,,,,,,,,,
=2000,2000,abaca,2000,943.490701,914.089347,11.424,10778.437768,11.424,10778.437768,0.0,0.0
=2000,2000,abaca,2005,943.490701,914.089347,6.016,5676.040057,6.016,5676.040057,0.0,0.0
=2000,2000,abaca,2010,943.490701,914.089347,0.509,480.236767,0.509,480.236767,0.0,0.0
=2000,2000,abaca,2015,943.490701,914.089347,0.509,480.236767,0.509,480.236767,0.0,0.0
=2000,2000,abaca,2020,943.490701,914.089347,0.509,480.236767,0.509,480.236767,0.0,0.0