# FABLE Pyculator 2021 Notebook Loop

This notebook uses the validated 2021 generated-model artifact. It intentionally uses a 2021 workbook path and a 2021 generated-model path. It does not fall back to the tracked 2020 generated model archive.

Expected local workbook artifact:

- `tmp/private-workbooks/2021_Open_FABLECalculator.xlsx`

Tracked compressed generated-model artifact:

- `examples/fable_2021/generated_fable_2021_model.py.xz`

Ignored generated-model working path:

- `tmp/generated-models/fable-2021/generated_fable_2021_model.py`

In [2]:
from pathlib import Path
import lzma
import shutil

from fable_pyculator import (
    DEFAULT_2021_GENERATED_MODEL_PATH,
    DEFAULT_2021_WORKBOOK_PATH,
    build_2021_notebook_spec,
    output_table_frame,
    run_2021_notebook_loop,
)


def find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for path in (current, *current.parents):
        if (path / "pyproject.toml").exists() and (path / "src" / "fable_pyculator").exists():
            return path
    raise RuntimeError("Could not find fable-pyculator repository root")


repo_root = find_repo_root(Path.cwd())
workbook_path = repo_root / DEFAULT_2021_WORKBOOK_PATH
generated_model_path = repo_root / DEFAULT_2021_GENERATED_MODEL_PATH
archive_path = repo_root / "examples" / "fable_2021" / "generated_fable_2021_model.py.xz"

if not generated_model_path.exists() and archive_path.exists():
    generated_model_path.parent.mkdir(parents=True, exist_ok=True)
    with lzma.open(archive_path, "rb") as source, generated_model_path.open("wb") as target:
        shutil.copyfileobj(source, target)

missing = [path for path in (workbook_path, generated_model_path) if not path.exists()]
ARTIFACTS_READY = not missing

print(f"Workbook: {workbook_path}")
print(f"Generated model: {generated_model_path}")
print(f"Compressed generated model archive: {archive_path}")
if missing:
    print("Missing local artifact(s):")
    for path in missing:
        print(f"- {path}")
else:
    print("Ready: 2021 workbook and generated model are available.")

Workbook: /srv/shared-data/gafar001/fable-pyculator/tmp/private-workbooks/2021_Open_FABLECalculator.xlsx
Generated model: /srv/shared-data/gafar001/fable-pyculator/tmp/generated-models/fable-2021/generated_fable_2021_model.py
Compressed generated model archive: /srv/shared-data/gafar001/fable-pyculator/examples/fable_2021/generated_fable_2021_model.py.xz
Ready: 2021 workbook and generated model are available.

Build the 2021 wrapper spec. This discovers workbook structure only; it does not generate the Modelwright Python model.

In [4]:
if ARTIFACTS_READY:
    spec = build_2021_notebook_spec(workbook_path)
    print(spec.workbook_id)
    print(len(spec.selection_controls), "selection controls")
    print(len(spec.scenario_definition_tables), "scenario definition tables")
    print(len(spec.output_tables), "output tables")
else:
    print("Restore the 2021 workbook and matching 2021 generated model before building the spec.")

fable-c-2021
16 selection controls
28 scenario definition tables
14 output tables

Run the matching 2021 generated model and render notebook outputs.

In [ ]:

if ARTIFACTS_READY:
    result = run_2021_notebook_loop(
        {"gdp_scen": "SSP1"},
        workbook_path=workbook_path,
        generated_model_path=generated_model_path,
        output_table_column_flavour_tags="OUTPUT-*",
        include_figures=False,
    )
    print(result.run.scenario_name)
    print(len(result.output_tables), "rendered output tables")
    print(len(result.headline_frames), "headline frames")
else:
    print("Skipped model run because required local artifacts are missing.")

In [6]:
if ARTIFACTS_READY:
    result = run_2021_notebook_loop(
        {"gdp_scen": "SSP1"},
        workbook_path=workbook_path,
        generated_model_path=generated_model_path,
        include_figures=False,
    )
    print(result.run.scenario_name)
    print(len(result.output_tables), "rendered output tables")
    print(len(result.headline_frames), "headline frames")
else:
    print("Skipped model run because required local artifacts are missing.")

scenario
14 rendered output tables
4 headline frames

Inspect a focused GHG table after the run.

In [14]:
if result is not None:
    display(result.output_tables["trade_resultstrade"].head())
else:
    display(Markdown("Skipped: run the model first."))

,PriceYear,PRODUCT,YEAR,ExportPrice,ImportPrice,ExportQ_targ,Exportvusd_targ,ExportQ_feas,Exportvusd_feas,ImportQ_feas,Importvusd
row,,,,,,,,,,,
=2000,None,None,None,None,None,11.424,None,11.424,None,0.0,None
=2000,None,None,None,None,None,6.016,None,6.016,None,0.0,None
=2000,None,None,None,None,None,0.509,None,0.509,None,0.0,None
=2000,None,None,None,None,None,0.509,None,0.509,None,0.0,None
=2000,None,None,None,None,None,0.509,None,0.509,None,0.0,None

In [15]:
if result is not None:
    display(result.output_tables["biodiversity_resultsbiodiv"].head())
else:
    display(Markdown("Skipped: run the model first."))

,YEAR,FAOForest,FAOOtherLand,FAOTotalLand,CalcForest,CalcNewForest,CalcOtherLand,FAOBiodivLnd,CalcBiodivForest,BiodivNewForest,CalcBiodivOtherLand,CalcBiodivLnd,BiodivTarget
row,,,,,,,,,,,,,
2000,None,None,None,None,172298.206759,0.0,81478.746997,None,None,None,None,None,None
2005,None,None,None,None,172132.203151,5000.0,103367.596139,None,None,None,None,None,None
2010,None,None,None,None,170081.348650,10000.0,87278.357661,None,None,None,None,None,None
2015,None,None,None,None,169029.117847,12000.0,79193.660535,None,None,None,None,None,None
2020,None,None,None,None,167736.229431,19800.0,67651.497034,None,None,None,None,None,None

In [10]:
if ARTIFACTS_READY:
    display(output_table_frame(result.run, "food_results_diets", column_flavour_tags="OUTPUT-*").head())
else:
    print("Skipped output inspection because required local artifacts are missing.")

,PROD_GROUP,YEAR,gr_trend,kcal_trend,fat_trend,prot_trend,gr_calc,kcal_calc,fat_calc,prot_calc,gr_healthy,kcal_healthy
row,,,,,,,,,,,,
CEREALS,None,None,389.703716,1397.825305,4.243112,28.261134,389.703716,1397.825305,4.243112,28.261134,None,None
CEREALS,None,None,397.850616,1427.614866,4.343846,28.820913,397.850616,1427.614866,4.343846,28.820913,None,None
CEREALS,None,None,399.632824,1434.034243,4.385593,28.836216,399.632824,1434.034243,4.385593,28.836216,None,None
CEREALS,None,None,389.036048,1396.008988,4.269303,28.071587,389.036048,1396.008988,4.269303,28.071587,None,None
CEREALS,None,None,378.439272,1357.983734,4.153013,27.306958,378.439272,1357.983734,4.153013,27.306958,None,None

In [13]:
if ARTIFACTS_READY:
    display(output_table_frame(result.run, "trade_resultstrade").head())
else:
    print("Skipped output inspection because required local artifacts are missing.")

,PriceYear,PRODUCT,YEAR,ExportPrice,ImportPrice,ExportQ_targ,Exportvusd_targ,ExportQ_feas,Exportvusd_feas,ImportQ_feas,Importvusd
row,,,,,,,,,,,
=2000,None,None,None,None,None,11.424,None,11.424,None,0.0,None
=2000,None,None,None,None,None,6.016,None,6.016,None,0.0,None
=2000,None,None,None,None,None,0.509,None,0.509,None,0.0,None
=2000,None,None,None,None,None,0.509,None,0.509,None,0.0,None
=2000,None,None,None,None,None,0.509,None,0.509,None,0.0,None